### PR TITLE
Moved wiki pages to LOOT's website

### PR DESCRIPTION
**Pull request by WrinklyNinja**
This PR:

* Retain's the wiki's commit history
* Converts the wiki's Markdown pages to HTML so that they display correctly on the website
* Deletes the transferred team members page
* Updates outdated content in the transferred pages
* Removes the wiki link from the site's sidebar

This is part of #51.

@Freso can you merge this if you're happy with what I've done?

### CODE REVIEW

**Comment by Freso** [comment]
Yep, I'll give it a look today or tomorrow. :)

**Comment by WrinklyNinja** [comment]
:alarm_clock: It's tomorrow! :persevere:

**Comment by Freso** [comment]
I'm actually sitting with it right now. :p

**Comment by Freso** [comment]
The version change on /docs/ doesn't seem to work for me running on localhost, and I don't like that /docs/help/ gives a plain directory listing, but I don't see any major issues, so I'm going to merge this and anything else can be fixed up once it's live.

**Comment by WrinklyNinja** [comment]
OK, sure. What browser are you using when testing the readme version selector?

I can add index pages for `/docshelp` `/docs/contributing` and `/docs/team`.

**Comment by Freso** [comment]
> OK, sure. What browser are you using when testing the readme version selector?

Firefox 45.0.1 (Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0)

**Comment by WrinklyNinja** [comment]
OK, I can replicate it, I'll get it fixed. I wonder what's going wrong...

**Comment by WrinklyNinja** [comment]
Oh, there's a bug in FF that prevents `<select>` elements firing `input` events...

**Comment by WrinklyNinja** [comment]
Index pages have been added and the selector has been fixed.

**Pull request merged**
